# Generated by Django 3.0.2 on 2020-01-15 20:18

from django.db import migrations


def add_default_exam_types(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Type = apps.get_model('answers', 'ExamType')
    Type.objects.using(db_alias).create(displayname='Exams', order=-100)
    Type.objects.using(db_alias).create(displayname='Transcripts', order=-99)
    Type.objects.using(db_alias).create(displayname='Midterms', order=-98)
    Type.objects.using(db_alias).create(displayname='Endterms', order=-97)
    Type.objects.using(db_alias).create(displayname='Finals', order=-96)


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_exam_types)
    ]
