# Generated by Django 3.0.4 on 2020-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_default_exam_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersection',
            name='name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
