# Generated by Django 3.0.4 on 2020-03-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0003_answersection_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersection',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
