# Generated by Django 3.0.4 on 2020-06-03 12:49

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0009_add_search_vector"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="answer",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="answers_ans_search__457a29_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="answers_com_search__02cfaa_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="answers_exa_search__525230_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="exampage",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="answers_exa_search__995090_gin"
            ),
        ),
    ]
