# Generated by Django 3.2 on 2021-04-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0010_add_gin_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersection',
            name='has_answers',
            field=models.BooleanField(default=True),
        ),
    ]
