# Generated by Django 4.1.13 on 2024-01-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("answers", "0015_alter_comment_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exam",
            name="finished_wiki_transfer",
        ),
        migrations.RemoveField(
            model_name="exam",
            name="legacy_solution",
        ),
    ]
