# Generated by Django 3.0.2 on 2020-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_default_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='semester',
            field=models.CharField(choices=[('--', '--'), ('FS', 'FS'), ('HS', 'HS'), ('Both', 'Both')], default='--', max_length=4),
        ),
    ]
