# Generated by Django 3.0.2 on 2020-04-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_categorymetadata'),
    ]

    sql = """
    CREATE VIEW categories_examcounts (id, exam_id, count_cuts, count_answered) AS
        SELECT row_number() OVER () as id,
            ae.id AS exam_id,
            (SELECT COUNT(*) FROM answers_answersection aas WHERE (aas.exam_id = ae.id)),
            (SELECT COUNT(*) FROM answers_answersection aas WHERE (aas.exam_id = ae.id AND EXISTS (
                SELECT aa.id FROM answers_answer aa WHERE aa.answer_section_id = aas.id
            )))
        FROM answers_exam ae
    ;
    """

    operations = [
        migrations.RunSQL('DROP VIEW IF EXISTS categories_examcounts;'),
        migrations.RunSQL(sql)
    ]
