# Generated by Django 3.0.2 on 2020-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='displayname',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
