# Generated by Django 3.0.4 on 2021-03-30 13:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("documents", "0002_auto_20210329_0928"),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="likes",
            field=models.ManyToManyField(
                related_name="liked_documents", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
