# Generated by Django 3.0.4 on 2021-04-15 14:59

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20210404_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
