# Generated by Django 3.2 on 2021-05-13 13:21

import django.contrib.postgres.indexes
from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20210415_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='api_key',
            field=models.CharField(default=documents.models.generate_api_key, max_length=1024),
        ),
    ]
