# Generated by Django 3.0.2 on 2020-03-28 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvotes', models.IntegerField()),
                ('downvotes', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
